### PR TITLE
Install make_differential_dfxml.py

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This patch series completes the implementation of something I had started before I went on vacation two weeks ago, and which I'd told @jgru and @simsong that I was about ~80% done on when my vacation started.

I see that in the intervening time when I wasn't checking email, [Pull Request 12](https://github.com/dfxml-working-group/dfxml_python/pull/12) was merged.  So, this patch series is also belated commentary on some of the effects.

The main purpose of this patch series is migrating `make_differential_dfxml.py`, and its tests, into the practices defined ~1 week ago and ~3 weeks ago.

As for the PR 12 commentary: In the end, I'm happy with what the name scheme has done as of the merge of PR 12.  I foresee some challenge with continuing to find such succinct names.

However, I must urge caution in continuing to change names of scripts.  I am aware of operationalized and research workflows, some years in development and/or operation, that use some of these programs.  A current project I'm working on makes use of what was formerly `walk_to_dfxml.py` and is now `dfxml_cwd`, and likewise for `make_differential_dfxml.py` that I've adjusted to be `dfxml_diff`.  These programs have never, before PR 12, changed their names.  (I think they had changed paths once before to resolve some intermingling issues with the C++ code base.)

Since this code base has not formally adopted [SEMVER](https://semver.org) yet, I don't feel this code base has gone against any commitments it's made.  The name change might cause some confusion for users - I had to field a 404 question for `walk_to_dfxml.py` today, which was inevitable with the repo move, but more confusing with script name having gone away.  Overall, I believe this induces discussion for `CONTRIBUTE.md`, to come in another Pull Request.

This patch series intentionally leaves the two exported commands that I've had a hand in in a form of rename-limbo.  The former `make_differential_dfxml.py` has been moved to `/dfxml/make_differential_dfxml/__init__.py`, but is installed as `dfxml_diff`.  This follows the partial rename where `walk_to_dfxml.py` is now exposed as `dfxml_cwd`.  This is leading me to think it may be better to move scripts back to `/dfxml/bin/${script_name}.py`, because the `${script_name}/__init__.py` practice was being used as a testing maturity indicator.  The slew of commands added to `setup.cfg` kind of undoes that value.  It seems I was not clear that I meant for scripts to stay outside of the `/dfxml` installable-files path until they received documentation and testing for stability.

I am fine with this PR being merged as-is, and having some discussion about file naming, testing requirements, and documentation requirements in the context of `CONTRIBUTE.md` before doing another batch of file moves.  @simsong, please merge if you agree.

### CODE REVIEW

**Review by simsong — APPROVED** [review]

**Comment by jgru** [comment]
Great to see progress again, @ajnelson-nist.

> However, I must urge caution in continuing to change names of scripts. I am aware of  operationalized and research workflows, some years in development and/or operation, that use some of these programs. A current project I'm working on makes use of what was formerly walk_to_dfxml.py and is now dfxml_cwd, and likewise for make_differential_dfxml.py that I've adjusted to be dfxml_diff. These programs have never, before PR 12, changed their names. (I think they had changed paths once before to resolve some intermingling issues with the C++ code base.)

I'm sorry to hear that! I was unsure, whether renaming `walk_to_dfxml.py` and `make_differential_dfxml.py` was a good idea, but I thought it might not pass the review, if it would be not. Furthermore, I assumed, that it is not a big deal, since not the names of the scripts itself, but the names of the installed commands were changed.
If you prefer to undo that, please let me know. I can work on a patch, reverting those changes.

> This is leading me to think it may be better to move scripts back to /dfxml/bin/${script_name}.py, because the ${script_name}/__init__.py practice was being used as a testing maturity indicator.

Do you mean, that those scripts should be moved outside of the actual package directory (again)?

> The slew of commands added to setup.cfg kind of undoes that value. It seems I was not clear that I meant for scripts to stay outside of the /dfxml installable-files path until they received documentation and testing for stability.

Okay, is it in your opinion preferable to not install the helper tools via `setup.cfg` at all and leave it up to the user to use them and put them into the own `$PATH` eventually?

Thanks already in advance.

Best regards
Jan

**Comment by simsong** [comment]
Sounds like there needs to be a clear policy regarding renaming, as well as file placement.

**Comment by ajnelson-nist** [comment]
Re: @simsong 

> I think there needs to be a clear policy regarding renaming, as well as file placement.

I tried writing `CONTRIBUTE.md` to indicate file paths and tool names would be features under the scope of backwards compatibility maintenance.  If I was too oblique, I can revise the file.

Re: @jgru 

> Great to see progress again, @ajnelson-nist.
> 
> > However, I must urge caution in continuing to change names of scripts. I am aware of  operationalized and research workflows, some years in development and/or operation, that use some of these programs. A current project I'm working on makes use of what was formerly walk_to_dfxml.py and is now dfxml_cwd, and likewise for make_differential_dfxml.py that I've adjusted to be dfxml_diff. These programs have never, before PR 12, changed their names. (I think they had changed paths once before to resolve some intermingling issues with the C++ code base.)
> 
> I'm sorry to hear that! I was unsure, whether renaming `walk_to_dfxml.py` and `make_differential_dfxml.py` was a good idea, but I thought it might not pass the review, if it would be not. Furthermore, I assumed, that it is not a big deal, since not the names of the scripts itself, but the names of the installed commands were changed.
> If you prefer to undo that, please let me know. I can work on a patch, reverting those changes.

Unfortunately, it was not as minor a matter as you perceived.  I've socialized these programs in conferences and communities, and/or cited them in papers over the years.  Changing the name hampers future discovery.  Again, some of this breakage was going to happen with reshuffling things to make a `pip`-installable package, but changing the name as well as the directory may make it too hard to find.

> 
> > This is leading me to think it may be better to move scripts back to /dfxml/bin/${script_name}.py, because the ${script_name}/**init**.py practice was being used as a testing maturity indicator.
> 
> Do you mean, that those scripts should be moved outside of the actual package directory (again)?

(Oh, interesting.  Github doesn't like the double-underscore in a file name.)

No, I think it's good to provide the scripts as resources accompanying the package.  Otherwise, to use the scripts, one would not only have to install the `dfxml` package, but also track the `dfxml_python` source tree.

I had meant that changing from `/bin/walk_to_dfxml.py` to `/dfxml/walk_to_dfxml/__init__.py` was less helpful than I thought it would be.  I found these cons:
* I've used a logging pattern for around a decade now that instantiates `_logger = logging.getLogger(os.path.basename(__file__))`, so I can tell what file emitted a log message.  If every command has the basename `__init__.py`, this makes development-time debugging a bit source-obfuscated.  (Particularly, `pip install -e` and debugging under the `/tests` directory is harder.)
* It looks inconsistent to put some tools under the `/dfxml/` directory, some under `/dfxml/bin/`.
* Like noted above, people looking for `walk_to_dfxml.py` because it was cited somewhere won't find a file of that name.  They'll find a directory if they think to cut the `.py` extension.

I thought that this would be a sufficient pro, but I now think I was wrong:
* By being in the `/dfxml/${script_name}/__init__.py` format, the tool would have "Graduated" in its maturity, having other qualities like unit tests and documentation.  (This was with an eye towards designating which features would need to maintain backwards compatibility.)
  - I now think this is better handled in two ways: Documentation (in `/dfxml/bin/README.md`), and having an installation line listed in the `setup.cfg`.

One other con is that I haven't yet found a need for another file to reside in a tool's source directory.  But, I don't have a lot of practice making complex Python tool-and-module directory hierarchies.

> 
> > The slew of commands added to setup.cfg kind of undoes that value. It seems I was not clear that I meant for scripts to stay outside of the /dfxml installable-files path until they received documentation and testing for stability.
> 
> Okay, is it in your opinion preferable to not install the helper tools via `setup.cfg` at all and leave it up to the user to use them and put them into the own `$PATH` eventually?

Yes, that is my opinion.  I'll be filing a patch to revert most of the additions to `setup.cfg`, and to adjust the documentation.

> 
> Thanks already in advance.
> 
> Best regards
> Jan

I'm happy we're talking through this.  Thank you, Jan.

**Comment by simsong** [comment]
Okay. Let’s put the names back. Please submit a PR


----
Sent from my phone.

On Aug 20, 2021, at 10:04 AM, Alex Nelson ***@***.***> wrote:

﻿
Re: @simsong

I think there needs to be a clear policy regarding renaming, as well as file placement.

I tried writing CONTRIBUTE.md to indicate file paths and tool names would be features under the scope of backwards compatibility maintenance. If I was too oblique, I can revise the file.

Re: @jgru

Great to see progress again, @ajnelson-nist.

However, I must urge caution in continuing to change names of scripts. I am aware of operationalized and research workflows, some years in development and/or operation, that use some of these programs. A current project I'm working on makes use of what was formerly walk_to_dfxml.py and is now dfxml_cwd, and likewise for make_differential_dfxml.py that I've adjusted to be dfxml_diff. These programs have never, before PR 12, changed their names. (I think they had changed paths once before to resolve some intermingling issues with the C++ code base.)

I'm sorry to hear that! I was unsure, whether renaming walk_to_dfxml.py and make_differential_dfxml.py was a good idea, but I thought it might not pass the review, if it would be not. Furthermore, I assumed, that it is not a big deal, since not the names of the scripts itself, but the names of the installed commands were changed.
If you prefer to undo that, please let me know. I can work on a patch, reverting those changes.

Unfortunately, it was not as minor a matter as you perceived. I've socialized these programs in conferences and communities, and/or cited them in papers over the years. Changing the name hampers future discovery. Again, some of this breakage was going to happen with reshuffling things to make a pip-installable package, but changing the name as well as the directory may make it too hard to find.

This is leading me to think it may be better to move scripts back to /dfxml/bin/${script_name}.py, because the ${script_name}/init.py practice was being used as a testing maturity indicator.

Do you mean, that those scripts should be moved outside of the actual package directory (again)?

(Oh, interesting. Github doesn't like the double-underscore in a file name.)

No, I think it's good to provide the scripts as resources accompanying the package. Otherwise, to use the scripts, one would not only have to install the dfxml package, but also track the dfxml_python source tree.

I had meant that changing from /bin/walk_to_dfxml.py to /dfxml/walk_to_dfxml/__init__.py was less helpful than I thought it would be. I found these cons:

I've used a logging pattern for around a decade now that instantiates _logger = logging.getLogger(os.path.basename(__file__)), so I can tell what file emitted a log message. If every command has the basename __init__.py, this makes development-time debugging a bit source-obfuscated. (Particularly, pip install -e and debugging under the /tests directory is harder.)
It looks inconsistent to put some tools under the /dfxml/ directory, some under /dfxml/bin/.
Like noted above, people looking for walk_to_dfxml.py because it was cited somewhere won't find a file of that name. They'll find a directory if they think to cut the .py extension.
I thought that this would be a sufficient pro, but I now think I was wrong:

By being in the /dfxml/${script_name}/__init__.py format, the tool would have "Graduated" in its maturity, having other qualities like unit tests and documentation. (This was with an eye towards designating which features would need to maintain backwards compatibility.)
I now think this is better handled in two ways: Documentation (in /dfxml/bin/README.md), and having an installation line listed in the setup.cfg.
One other con is that I haven't yet found a need for another file to reside in a tool's source directory. But, I don't have a lot of practice making complex Python tool-and-module directory hierarchies.

The slew of commands added to setup.cfg kind of undoes that value. It seems I was not clear that I meant for scripts to stay outside of the /dfxml installable-files path until they received documentation and testing for stability.

Okay, is it in your opinion preferable to not install the helper tools via setup.cfg at all and leave it up to the user to use them and put them into the own $PATH eventually?

Yes, that is my opinion. I'll be filing a patch to revert most of the additions to setup.cfg, and to adjust the documentation.

Thanks already in advance.

Best regards
Jan

I'm happy we're talking through this. Thank you, Jan.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ajnelson-nist** [comment]
Shall do.

**Comment by jgru** [comment]
> I've socialized these programs in conferences and communities, and/or cited them in papers over the years. 

I know and this is why I appreciate `dfxml` very much. However, I think, that the somehow inconsistent naming and project structure as well as the sparse documentation did not kind of meet its value as a tool for the forensics community and it was my solely good intent to better that.

> Changing the name hampers future discovery. 
I thought that some SEMVER and corresponding change documentation could mitigate that, but I totally understand, that this is a major impediment for you as the author.

> I thought that this would be a sufficient pro, but I now think I was wrong:
> <snip>
> I now think this is better handled in two ways: Documentation (in /dfxml/bin/README.md), and having an installation line listed in the setup.cfg.

After your explanation of the reasoning behind this decision, I think, that this seems like a very valid decision. (At least as far as I can tell with my limited insight into the project(

> Yes, that is my opinion. I'll be filing a patch to revert most of the additions to setup.cfg, and to adjust the documentation.

Sorry to hear, that I caused work. :( Please excuse the last PR... 
If you want to delegate some tasks, please drop me a message.

**Comment by ajnelson-nist** [comment]
No worries on the discussion length & work.  We're helping the project grow.

As for the name scheme point: Names are hard, classic problem.  I have a practice of doing tool mapping with projects following the name `_to_dfxml`, such as with the [ddrescue Mapfile to DFXML project](https://github.com/ajnelson-nist/gddrescue_mapfile_to_dfxml).  This is another reason I wanted to keep the `walk_to_dfxml` name.
But, that scheme only works when some thing is being mapped into DFXML.  It doesn't quite work for DFXML consumptive tools, or in the case of `make_differential_dfxml`, something consuming and producing DFXML.

I did like your first try at a round of tools following the pattern `dfxml_${something}`.  It might still have some legs.  But, we should be mindful of tool history.

**Comment by jgru** [comment]
> No worries on the discussion length & work. We're helping the project grow.

Good to hear. =)

> But, we should be mindful of tool history.

Yes, in retrospect, this argument should have brought up right at the beginning, given the references in academic literature. 
I'm looking forward for further maturing of dfxml, but I think making it a self contained libary with some "loosely coupled" tools sounds well.

**Pull request merged**
