### PR TITLE
Modify directory structure to separate the core-module from the tools

### PR DESCRIPTION
**Pull request by jgru**
Dear Simson, dear Alex, 

this PR modifies the directory structure of the code to make it more modular and accessible for inexperienced users. 
The core module was separated from the various tools and the necessary modifications to the build system and the unit tests were performed in order to ensure correct functionality after changing the file locations. 

This is another advance to try to make the Python-codebase more easy to deploy/install and overall more mature.

Best regards   
    Jan

### CODE REVIEW

**Comment by simsong** [comment]
I'll let @ajnelson-nist handle this. I'm handling the C++ stuff.

**Comment by ajnelson-nist** [comment]
@jgru ,

I've had to focus on another project before a conference next week that will be taking my attention for at least four days.  I apologize, I probably won't be able to look at this or the other PR before then.

--Alex

**Comment by jgru** [comment]
> @jgru ,
> 
> I've had to focus on another project before a conference next week that will be taking my attention for at least four days. 

I can think of which conference this is. Way higher priority obviously! :)

> I apologize, I probably won't be able to look at this or the other PR before then.
> 
> --Alex

Absolutely no problem, @ajnelson-nist! Thanks for getting back to me!

**Comment by jgru** [comment]
Hey, this is just friendly ping, so that this PR does not get lost. 
---
Jan

**Comment by simsong** [comment]
I can review it

**Review by simsong — APPROVED** [review]
Looks reasonable

**Comment by ajnelson-nist** [comment]
Thanks, @simsong , I got surprised with a project earlier this week.

**Comment by jgru** [comment]
Thank you very much for the review and the resulting merge, @simsong!

**Comment by ajnelson-nist** [comment]
Ah, dear, on doing some belated testing with this, I fear that it may not have been helpful to move tools outside of the `/dfxml` directory.  There may be some complication with package building and defining console entry points.  Updating PR coming.

**Comment by simsong** [comment]
Can you include your tests in the tests directory so we can automatically run them as part of the CI process?

**Comment by ajnelson-nist** [comment]
Yes.  I'm writing the PR now.

**Pull request merged**
