### PR TITLE
Adjust test strategy

### PR DESCRIPTION
**Pull request by ajnelson-nist**
The first two patches have descriptions of the rationale for this patch series.  @simsong , I would like you to merge this PR if you agree with this direction.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@jgru , FYI - there was a missed rename in your prior patch that wasn't caught by CI.  A new test has been added.

**Review by simsong — APPROVED** [review]
Looks good. We should add pylint to the CI checks.

**Comment by simsong** [comment]
> Looks good. We should add pylint to the CI checks.

and codecov.

**Comment by jgru** [comment]
> @jgru , FYI - there was a missed rename in your prior patch that wasn't caught by CI. A new test has been added.

Sorry and thank you very much for catching!

**Pull request merged**
