### PR TITLE
Fix 'make check'

### PR DESCRIPTION
**Pull request by jgru**
Dear Simson, 

this commit fixes the tests in the subdirectory `python/tests` so that they can be run with `make check` manually and in the CI. 
To accomplish this, several smaller changes have been made to the test scripts as well as old tests referrring to
inexistent files have been removed. In addition, the directory structure was cleaned up and the CI-yml was modified to run `make check` in the course of the whole pipeline on pushes and on PRs also. 

As a sidenote, what do you think of renaming the `python`-directory to something else like `dfxml` or `pydfxml`? 

Thank you already in advance for considering this addition. I hope, that these changes correspond to your ideas. 
I think it is a leap forward, since the more automatic testing the better. 

Best regards  
Jan

### CODE REVIEW

**Comment by simsong** [comment]
Thanks for the PR! Since this is @ajnelson-nist's code, I'm asking to sign off on the code review.

**Comment by jgru** [comment]
> Thanks for the PR! Since this is @ajnelson-nist's code, I'm asking to sign off on the code review.

Sure! Looking forward for his review.

**Comment by jgru** [comment]
I have a further question -- not related to this PR --  regarding the installation of the supplied scripts/tools:
What do you think, which tools should be installed? As I am only using `fiwalk` and `idifference2` on a regular basis I am wondering, which tools could/should be omitted during installation?

**Comment by ajnelson-nist** [comment]
Thanks for the PR!  I'll look over it this afternoon, running a meeting this morning.

Some of what I think is happening in the PR and what you suggested---promoting the `python/` directory's contents to top-level, setting up `setup.cfg` to make things work well with `pip`---I probably would have made more progress on if this split didn't kick off at the beginning of a holiday weekend.  We seem to have a similar usability vision.

**Comment by simsong** [comment]
> I have a further question -- not related to this PR -- regarding the installation of the supplied scripts/tools:
> What do you think, which tools should be installed? As I am only using `fiwalk` and `idifference2` on a regular basis I am wondering, which tools could/should be omitted during installation?

What is your use case for `fiwalk` ? Is it solely for use with `idifference2`, or are you also using it with `bulk_extractor` ?

**Comment by jgru** [comment]
> Thanks for the PR! I'll look over it this afternoon, running a meeting this morning.

You're welcome, @ajnelson-nist, happy to help (hope to do so at least :D )! 

> Some of what I think is happening in the PR and what you suggested---promoting the `python/` directory's contents to top-level, setting up `setup.cfg` to make things work well with `pip`---I probably would have made more progress on if this split didn't kick off at the beginning of a holiday weekend. We seem to have a similar usability vision.

Sounds good, as I want to package dfxml's Python implementen for Debian as well, I am explicitly squinting at a smooth build process with distutils. 

I was unsure about moving the sources to the toplevel, since the various tools would make it untidy I think and putting those in a subdirectory (parallel to the dfxml-module-dir) would not work without modifications. What are your thoughts on this?

> What is your use case for fiwalk ? Is it solely for use with idifference2, or are you also using it with bulk_extractor ?

I am using fiwalk for parsing images and generating dfxml-output, which then can be compared with idifference. 
I didn't use it in combination with bulk_extraction. I was just wondering, which tools bring a certain "production value" and should be installed "system-wide", so that I could work on the setup.py-file. What do you consider to be valuable tools and which not so much (I'm thinking of xmirror or TCPFlowObjects e.g.), @simsong ?

**Review by ajnelson-nist — APPROVED** [review]
These changes all look good to me, except this should work in macOS as well.  Some of the changes also highlight how lessons learned over the last years should be brought in.

It's good enough to merge.  I'll leave an issue to restore tests for macOS.

**Pull request merged**
