### PR TITLE
Use setup cfg, single-source package version, and install walk_to_dfxml

### PR DESCRIPTION
**Pull request by ajnelson-nist**
The patches each contain notes.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@jgru , this patch series meets you in the middle on your patch that moved the script files around.  I vaguely recall a mechanism to find installable commands outside of the top package directory, but could not find the documentation again.  So, I am proposing we move commands intended to be on `$PATH` back under the `/dfxml` directory, following the file name pattern `/dfxml/$command/__init__.py` that I know from prior experience works with `setup.cfg`.  If you have a functional alternative that works with how you moved things to `/bin`, I would be interested in hearing it.

@simsong , meanwhile, I request this be merged if you approve.  Even if the `walk_to_dfxml` script bounces back to `/bin`, I'm a bit more at peace having upgraded one of my old tests.

**Comment by jgru** [comment]
> @jgru , this patch series meets you in the middle on your patch that moved the script files around. I vaguely recall a mechanism to find installable commands outside of the top package directory, but could not find the documentation again. So, I am proposing we move commands intended to be on `$PATH` back under the `/dfxml` directory, following the file name pattern `/dfxml/$command/__init__.py` that I know from prior experience works with `setup.cfg`. If you have a functional alternative that works with how you moved things to `/bin`, I would be interested in hearing it.

Thanks for moving this forward! Actually I am only aware of how to install scripts in a separate `bin`-directory it with `setup.py`. Since I did not find documentation of installing scripts in a sibling-directory, I can't propose another solution. The one proposed by you seems to be apt though.

**Comment by jgru** [comment]
Are there any news on this? 
>So, I am proposing we move commands intended to be on $PATH back under the /dfxml directory, following the file name pattern /dfxml/$command/__init__.py that I know from prior experience works with setup.cfg. If you have a functional alternative that works with how you moved things to /bin, I would be interested in hearing it.

If this PR gets merged, I am willing to realize the proposed task.

**Review by simsong — APPROVED** [review]

**Comment by simsong** [comment]
> Are there any news on this?
> 
> > So, I am proposing we move commands intended to be on $PATH back under the /dfxml directory, following the file name pattern /dfxml/$command/**init**.py that I know from prior experience works with setup.cfg. If you have a functional alternative that works with how you moved things to /bin, I would be interested in hearing it.
> 
> If this PR gets merged, I am willing to realize the proposed task.

Since you are actually *willing to work on this project*, I'm highly motivated to accept your pull requests! Sorry for the delay.

**Comment by jgru** [comment]
> Since you are actually _willing to work on this project_, I'm highly motivated to accept your pull requests! Sorry for the delay.

Great! Thanks for considering those.

**Pull request merged**
